# Generated by Django 5.0.7 on 2024-07-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('other', 'others')], max_length=10)),
            ],
        ),
    ]
